# Project-specific golangci-lint configuration for truerpc-landing
# This file contains only project-specific overrides and will be merged with base config

linters:
  settings:
    goimports:
      local-prefixes: github.com/truewebber/kdmid-queue-checker
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/truewebber/kdmid-queue-checker)
        - blank
        - dot
