apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    repo: "github_com__truewebber__kdmid_queue_checker"
    app: "kdmid_queue_checker"
spec:
  replicas: {{ .Values.minReplicaCount }}
  selector:
    matchLabels:
      repo: "github_com__truewebber__kdmid_queue_checker"
      app: "kdmid_queue_checker"
  template:
    metadata:
      annotations:
        checksum: {{ .Values | sha1sum }}
      labels:
        repo: "github_com__truewebber__kdmid_queue_checker"
        app: "kdmid_queue_checker"
    spec:
      containers:
        - name: checker
          image: "docker pull ghcr.io/truewebber/kdmid-queue-checker:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.app.metricsPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              port: {{ .Values.app.metricsPort }}
              path: /metrics
            initialDelaySeconds: 20
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              port: {{ .Values.app.metricsPort }}
              path: /metrics
            initialDelaySeconds: 15
            timeoutSeconds: 9
          resources:
            requests:
              memory: "80Mi"
              cpu: "75m"
            limits:
              memory: "160Mi"
              cpu: "150m"
          volumeMounts:
            - mountPath: "/opt"
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
