apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "kdmid_queue_checker"
  annotations:
    repo: "https://github.com/truewebber/kdmid_queue_checker"
stringData:
  two_captcha_api_key: "{{ .Values.app.two_captcha_api_key }}"
  artifacts_directory: "{{ .Values.app.artifacts_directory }}"
  recipient_storage_directory: "{{ .Values.app.recipient_storage_directory }}"
  recipient_storage_limit: "{{ .Values.app.recipient_storage_limit }}"
  telegram_bot_token: "{{ .Values.app.telegram_bot_token }}"
  proxy_url: "{{ .Values.app.proxy_url }}"
