apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "kdmid_queue_checker"
  annotations:
    repo: "https://github_com/truewebber/kdmid_queue_checker"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.app.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: "kdmid_queue_checker"
